version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0

  pre_build:
    commands:
      - echo Restore started
      - cd src
      - dotnet restore

  build:
    commands:
      - echo Build started
      - dotnet publish -c Release -o output

artifacts:
  files:
    - '**/*'
  base-directory: src/output
